config/routes.rb
Rails.application.routes.draw do
  resources :to_dos
  root to: 'home#index'

  get 'about', to: 'home#about'

  resources :users, only: [:new, :create]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'logout', to: 'sessions#logout'
  

end

app/models/to_do.rb
class ToDo < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :to_dos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id

      redirect_to '/welcome'
    else 
      redirect_to '/login'
    end
  end

  def logout
    session[:user_id] = nil 
    redirect_to '/login'
  end

  def welcome
  end
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  before_action :set_to_do, only: [:show, :edit, :update, :destroy]
  before_filter :authorized

  # GET /to_dos
  # GET /to_dos.json
  def index
    @to_dos = current_user.to_dos
  end

  # GET /to_dos/1
  # GET /to_dos/1.json
  def show
  end

  # GET /to_dos/new
  def new
    @to_do = ToDo.new
  end

  # GET /to_dos/1/edit
  def edit
  end

  # POST /to_dos
  # POST /to_dos.json
  def create
    @to_do = ToDo.new(to_do_params)
    @to_do.user = current_user

    respond_to do |format|
      if @to_do.save
        format.html { redirect_to @to_do, notice: 'To do was successfully created.' }
        format.json { render :show, status: :created, location: @to_do }
      else
        format.html { render :new }
        format.json { render json: @to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /to_dos/1
  # PATCH/PUT /to_dos/1.json
  def update
    respond_to do |format|
      if @to_do.update(to_do_params)
        format.html { redirect_to @to_do, notice: 'To do was successfully updated.' }
        format.json { render :show, status: :ok, location: @to_do }
      else
        format.html { render :edit }
        format.json { render json: @to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /to_dos/1
  # DELETE /to_dos/1.json
  def destroy
    @to_do.destroy
    respond_to do |format|
      format.html { redirect_to to_dos_url, notice: 'To do was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_to_do
      @to_do = ToDo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def to_do_params
      params.require(:to_do).permit(:title, :description, :completed)
    end

    def authorized
      redirect_to '/login' unless logged_in?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hi!</h1>
  <p class="lead">Welcome to your ToDo App!</p>
  <hr class="my-4">
  <p>Its built using Ruby on Rails 4.2 and Bootstrap 4.</p>
  <a class="btn btn-primary btn-lg" href="/about" role="button">Learn more</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <a class="navbar-brand" href="#">ToDo App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'About', about_path, class: 'nav-link' %>
          </li>
          <% if logged_in?%>
            <li class="nav-item">
              <%= link_to 'ToDos', to_dos_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', logout_path, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Register', new_user_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Login', login_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <br/>
      <%= yield %>
    </div><!-- /.container -->
  </body>
</html>

app/views/to_dos/_form.html.erb
<%= form_for(@to_do) do |f| %>
  <% if @to_do.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@to_do.errors.count, "error") %> prohibited this to_do from being saved:</h2>

      <ul>
      <% @to_do.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div>
    <%= f.label :completed %>
    <%= f.check_box :completed, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/to_dos/edit.html.erb
<h1>Editing To Do</h1>

<%= render 'form' %>

<%= link_to 'Show', @to_do %> |
<%= link_to 'Back', to_dos_path %>

app/views/to_dos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing To Dos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Completed</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @to_dos.each do |to_do| %>
      <tr>
        <td><%= to_do.title %></td>
        <td><%= to_do.description %></td>
        <td><%= to_do.completed %></td>
        <td><%= link_to 'Show', to_do %></td>
        <td><%= link_to 'Edit', edit_to_do_path(to_do) %></td>
        <td><%= link_to 'Destroy', to_do, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New To do', new_to_do_path, class: 'btn btn-primary' %>

app/views/to_dos/new.html.erb
<h1>New To Do</h1>

<%= render 'form' %>

<%= link_to 'Back', to_dos_path %>

app/views/to_dos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @to_do.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @to_do.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @to_do.completed %>
</p>

<%= link_to 'Edit', edit_to_do_path(@to_do) %> |
<%= link_to 'Back', to_dos_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Register</h1>
<p>Enter your details below</p>

<%= form_for @user do |f|%>
  <div class="form-group">
    <%= f.label :email%>
    <%= f.email_field :email, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label :password%>
    <%= f.password_field :password, class: 'form-control'%>
  </div>
  <button type="submit" class="btn btn-primary btn-block">Register</button>
<% end %>